### ISSUE TITLE
b vector type error

### ISSUE THREAD

**Issue by rmcarthur** [rickecon/OGstochinc#3]
So the self.b attribute is currently a list of numpy arrays, which seems silly. I think it makes most sense to change them all to numpy arrays. (or possibly pandas). What is our data-frame convention on this? Lists, numpy arrays, pandas?

**Comment by rickecon** [comment]
I don't understand the difference between a list of numpy arrays and "...them all to numpy arrays." I think we only use pandas when there is an empirical component in which we are interacting with real world data. I think we stay with numpy arrays when working with numerical objects in the theory. Let's get to the bottom of this before I merge the corresponding PR. @drexmca @JustinGardiner
